/**:
  ros__parameters:
    min_longitudinal_offset: -5.0
    max_longitudinal_offset: 20.0
    min_lateral_offset: -10.0
    max_lateral_offset: 10.0
    min_height_offset: -2.0
    max_height_offset: 3.0
