sensor_kit_base_link:
  camera0/camera_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  
  # Fairy Lidar
  fairy_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0 
    pitch: 0.0 
    yaw: 0.0

  # E1R Lidar
  e1r_base_link:
    x: 0.729291
    y: 0.0498612
    z: -0.906721
    roll: -0.00971123
    pitch: -0.0119282 
    yaw: 0.0267976

  # Airy Lidar Left
  airy_left_base_link:
    x: -0.0299814
    y: 0.217083
    z: -0.41219
    roll: -1.11875
    pitch: 1.58005
    yaw: 0.468354

  # Airy Lidar Right
  airy_right_base_link:
    x: -0.0373976
    y: -0.226064
    z: -0.384485
    roll: 2.44512                                          
    pitch: 1.58783
    yaw: 0.940352 
    
  # XSens GNSS
  imu_link:
    x: 0.45
    y: -0.035
    z: -0.639
    roll: 0.0
    pitch: 0.0
    yaw: 0.0