sensor_kit_base_link:
  camera0/camera_link:
    x: 0.072836
    y: 0.024726
    z: -0.569802
    roll: 1.581131
    pitch: -0.052355
    yaw: 1.734129
  
  # Fairy Lidar
  fairy_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0 
    pitch: 0.0 
    yaw: 0.0

  # E1R Lidar
  e1r_base_link:
    x: 0.730976
    y: 0.0187822
    z: -0.906737
    roll: -0.0137271
    pitch: -0.00425854 
    yaw: 0.0282072

  # Airy Lidar Left
  airy_left_base_link:
    x: -0.0351711
    y: 0.229565
    z: -0.414868
    roll: -1.47046
    pitch: 1.58922
    yaw: 0.119637

  # Airy Lidar Right
  airy_right_base_link:
    x: -0.0228983 
    y: -0.249763
    z: -0.386253
    roll: 1.73569                                           
    pitch: 1.59482
    yaw: 0.229507
    
  # XSens GNSS
  imu_link:
    x: 0.45
    y: -0.035
    z: -0.639
    roll: 0.0
    pitch: 0.0
    yaw: 0.0