sensor_kit_base_link:
  
  # Frame for Robosense AC1 lidar and imu
  rslidar:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  
  # Frame for Robosense AC1 camera
  rgb:
    x: 0.0043
    y: 0.0
    z: -0.0269
    roll: 0.0
    pitch: 0.0
    yaw: 0.0